### ISSUE TITLE
Is cache interval for blobfuse (--file-cache-timeout-in-seconds) supported?

### ISSUE THREAD

**Issue by dharmeshkakadia** [Azure/kubernetes-volume-drivers#4]
Mentioned here : https://github.com/Azure/azure-storage-fuse#mount-options

It allows the how long the file cache is valid. This is very useful for large files.

**Comment by andyzhangx** [comment]
not yet, I will implement that, maybe I could add a new field `mountOptions` and you could add arbitrary options in that field?
```
    flexVolume:
      driver: "azure/blobfuse"
      readOnly: false
      secretRef:
        name: blobfusecreds
      options:
        container: CONTAINER-NAME
        tmppath: /tmp/blobfuse
        mountOptions: "..."
```
