### ISSUE TITLE
version 1.0.3 broke our SMB FlexVolume mount

### ISSUE THREAD

**Issue by shicholas** [Azure/kubernetes-volume-drivers#55]
**What happened**:

We have the SMB FlexVolume mount installed as a DaemonSet in our AKS Kubernetes Cluster. In our spec, we had the following:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"k8s-app":"smb"},"name":"smb-flexvol-installer","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"name":"smb"}},"template":{"metadata":{"labels":{"name":"smb"}},"spec":{"containers":[{"env":[{"name":"INSTALL_DEPS","value":"true"}],"image":"mcr.microsoft.com/k8s/flexvolume/smb-flexvolume:1.0.2","imagePullPolicy":"IfNotPresent","name":"smb-flexvol-installer","volumeMounts":[{"mountPath":"/etc/kubernetes/volumeplugins/","name":"volplugins"},{"mountPath":"/var/log/","name":"varlog"}]}],"nodeSelector":{"beta.kubernetes.io/os":"linux"},"volumes":[{"hostPath":{"path":"/var/log/"},"name":"varlog"},{"hostPath":{"path":"/etc/kubernetes/volumeplugins/","type":"DirectoryOrCreate"},"name":"volplugins"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: smb
  name: smb-flexvol-installer
  selfLink: /apis/apps/v1/namespaces/kube-system/daemonsets/smb-flexvol-installer
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: smb
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: smb
    spec:
      containers:
      - env:
        - name: INSTALL_DEPS
          value: "true"
        image: mcr.microsoft.com/k8s/flexvolume/smb-flexvolume
        imagePullPolicy: IfNotPresent
        name: smb-flexvol-installer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/volumeplugins/
          name: volplugins
        - mountPath: /var/log/
          name: varlog
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log/
          type: ""
        name: varlog
      - hostPath:
          path: /etc/kubernetes/volumeplugins/
          type: DirectoryOrCreate
        name: volplugins
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0
```

When creating new nodes in our cluster, the daemonset pulled the latest version of the SMB Image, which as of yesterday was `1.0.3`. This broke our environment with the following error when starting new containers:

```
9m13s       Warning   FailedMount        pod/****-xdqnm      MountVolume.SetUp failed for volume "****" : mount command failed, status: Failure, reason: Failed to mount device at /var/lib/kubelet/pods/7f386ade-18b6-4288-b374-6a9a0953358d/volumes/microsoft.com~smb/****, user:smbguest, //<IP>/sftp, error log:/etc/kubernetes/volumeplugins/microsoft.com~smb/smb: 66: /etc/kubernetes/volumeplugins/microsoft.com~smb/smb: /usr/sbin/mount.cifs: not found
3m43s       Warning   FailedMount        pod/****-deployment-85f75c77f7-xdqnm      Unable to attach or mount volumes: unmounted volumes=[****], unattached volumes=[**** default-token-mhqq5]: timed out waiting for the condition
17m         Warning   FailedMount        pod/****-deployment-85f75c77f7-xdqnm      Unable to attach or mount volumes: unmounted volumes=[****], unattached volumes=[default-token-mhqq5 ****]: timed out waiting for the condition
```

**What you expected to happen**:

We expect changes to the underlying images managed by this repo and AKS to not break our environment. We were able to fix this by fixing the image to by making the change in the DaemonSet above.

```
        image: mcr.microsoft.com/k8s/flexvolume/smb-flexvolume:1.0.2
```

**How to reproduce it**:

You might be able to reproduce this with the following Kubernetes deployment YAML:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api
      tier: app
  template:
    spec:
      terminationGracePeriodSeconds: 500
      volumes:
      - name: smbMount
        flexVolume:
          driver: microsoft.com/smb
          secretRef:
            name: smbcreds
          options:
            source: "//IP/sftp-server/sftp"
            mountoptions: vers=3.0,dir_mode=0777,file_mode=0777
      containers:
        # specify containers
```

**Anything else we need to know?**:

We realize we are using FlexVolumes instead of CSI, if our problem is unique to us, then perhaps this can be an issue.

**Environment**:
- Kubernetes version (use `kubectl version`): Client 1.15, Server 1.16
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`): Ubuntu 16.04.6
- Install tools: AKS Setk
- Others:
