### ISSUE TITLE
blobFUSE flexVolume README example problems

### ISSUE THREAD

**Issue by ohthehugemanatee** [Azure/kubernetes-volume-drivers#7]
I followed the README instructions using a PV/PVC, but the flexVolume won't attach to the pod in the end. Even using the example files (with required modifications eg container). `kubectl describe pod nginx-flex-blobfuse-pvc` gives:

`MountVolume.SetUp failed for volume "pv-blobfuse-flexvol" : mount command failed, status: Failure, reason: validation failed, error log:accountname is empty`

It does seem to work when it's a dynamic claim (eg `nginx-flex-blobfuse.yaml`), but that example doesn't let you set the size of the claim. It defaults to 30Gi.

The secret does exist, and I can validate that it's correct with `kubectrl describe secret blobfusecreds`. Not sure how to proceed debugging here.

**Comment by andyzhangx** [comment]
error logs says `accountname is empty`, are you using `accountname` keyword in `kubectl create secret` command?
```
kubectl create secret generic blobfusecreds --from-literal accountname=ACCOUNT-NAME --from-literal accountkey="ACCOUNT-KEY" --type="azure/blobfuse"
```

You may provide `kubectrl describe secret blobfusecreds` output.

**Comment by andyzhangx** [comment]
Besides that, there is no size concept for azure storage, it has only a size limit which is very big, size in PVC is only a tag, cannot prevent you to exceed that size.

**Comment by ohthehugemanatee** [comment]
Thanks for the fast response! 

```
$ kubectl describe secret blobfusecreds 

Name:         blobfusecreds
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  azure/blobfuse

Data
====
accountkey:   88 bytes
accountname:  23 bytes
```

Looks OK to me. I can also use `kubectl get secret blobfusecreds -o yaml` and validate that the accountkey and accountname are correct (base64 encoded versions of the raw values I input). Not to mention, those creds HAVE to be OK for it to work in the dynamic claim.

Regarding the size, what I mean is that the mounted device in the container is seen (by `df -h`) as 30G in size. In the PV/C method in the README, you get to explicitly set the size of the volume and claim.

Can you reproduce using the demo files?

**Comment by ohthehugemanatee** [comment]
<sigh> I re-created everything today and it DOES mount now. So I must have had a typo or similar stupid issue.

BUT `df -h` still reports the funny device size. Actually I noticed that it's reporting the same used and total as the root device. So I'm not at all certain that it's actually using the blobstore. 

```
$ df -h

Filesystem                                                                                                   Size  Used Avail Use% Mounted on
overlay                                                                                                       30G  9.4G   20G  33% /
tmpfs                                                                                                        3.5G     0  3.5G   0% /dev
tmpfs                                                                                                        3.5G     0  3.5G   0% /sys/fs/cgroup
/dev/sda1                                                                                                     30G  9.4G   20G  33% /etc/hosts
shm                                                                                                           64M     0   64M   0% /dev/shm
blobfuse                                                                                                      30G  9.4G   20G  33% /var/www/html/data
//nextcloudstorageaccount.file.core.windows.net/kubernetes-dynamic-pvc-4a1d1fbb-c36a-11e8-a7a2-2aa91002eab5   20G  184M   20G   1% /var/www/html/config
tmpfs                                                                                                        3.5G   12K  3.5G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                        3.5G     0  3.5G   0% /sys/firmware
```
For reference, here is the config:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blobfuse-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: blobfusecreds
    options:
      container: myblobcontainer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blobfuse-flexvol
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: pv-blobfuse-flexvol
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-nextcloud
  labels:
    app: azure-nextcloud
spec:
  selector:
    matchLabels:
      app: azure-nextcloud
      tier: frontend
  template:
    metadata:
      labels:
        app: azure-nextcloud
        tier: frontend
    spec:
      initContainers:
        - name: config-clone
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/ohthehugemanatee/nextcloud-config
            - /config
          securityContext:
            runAsUser: 1 
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: config-data
              mountPath: /config
      containers:
      - name: azure-nextcloud
        image: nextcloud
        volumeMounts:
          - name: flexvol-mount
            mountPath: /var/www/html/data
          - name: persistent-config
            mountPath: /var/www/html/config
          - name: config-data
            mountPath: /var/www/html/config/custom.config.php
            subPath: custom.config.php
        ports:
        - containerPort: 80
          name: nextcloud
      volumes:
        - name: flexvol-mount
          persistentVolumeClaim:
            claimName: pvc-blobfuse-flexvol
        - name: persistent-config
          persistentVolumeClaim:
            claimName: azurefile
        - name: config-data
          emptyDir: {}
```

How can I validate that it's mounting from the blobstore? Is it possible that it's failing over to loopback-mounting the root drive or something?
