### ISSUE TITLE
Can't install correctly smb-flexvol

### ISSUE THREAD

**Issue by SebastienHo** [Azure/kubernetes-volume-drivers#70]
**What happened**: 

I intend to install smb-flexvol using th efollowing command : 

kubectl apply -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/smb/deployment/smb-flexvol-installer.yaml

I have 4 pods created one is in bad state : 

![image](https://user-images.githubusercontent.com/3601250/86799237-03c0e780-c072-11ea-9f52-075d694b382c.png)

Can you help me?

**Comment by andyzhangx** [comment]
looks like there is sth wrong with your cluster. And we suggest using https://github.com/kubernetes-csi/csi-driver-smb

**Comment by SebastienHo** [comment]
Thanks Andy,

Using the plugin I was able to create the PV and the PVC 👍 

![image](https://user-images.githubusercontent.com/3601250/87040730-6f7d8e80-c1f1-11ea-96a0-e8399b30dd77.png)

![image](https://user-images.githubusercontent.com/3601250/87040778-8328f500-c1f1-11ea-8d3e-eec6068529a9.png)

 I am not able to use the volume within a deployment :

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: publishing-orchestrator-job
    app.kubernetes.io/version: "{version}"
    app.kubernetes.io/component: web
    app.kubernetes.io/environment: beta
  name: publishing-orchestrator-job-deployment
  namespace: beta
spec:
  replicas: 1
  template:
    metadata:
      name: publishing-orchestrator-job
      labels:
        app: publishing-orchestrator-job
        name: publishing-orchestrator-job
    spec:
      containers:
      - name: publishing-orchestrator-job
        image: tracepartsdockerrepo.azurecr.io/moon-publishingorchestrator.job-beta:{version}
        imagePullPolicy: "Always"
        ports:
          - containerPort: 80
            name: pod-port
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Beta
        - name: DLL_NAME
          value: PublishingOrchestrator.job.dll
        volumeMounts:
          - name: test
            mountPath: /data
      volumes:
        - name: test
          flexVolume:
            driver: "microsoft.com/smb"
            secretRef:
              name: smbcreds
            options:
              source: "//172.16.1.43/publishingstudio$$"
              mountoptions: "vers=2.0,dir_mode=0777,file_mode=0777"   
``` 

I get the following message 

MountVolume.MountDevice failed for volume "pv-smb" : rpc error: code = Internal desc = volume(publishingstudio_smb) mount "//172.16.1.43/publishingstudio$" on "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount" failed with mount failed: exit status 32 Mounting command: mount Mounting arguments: -t cifs -o dir_mode=0777,file_mode=0777,vers=2.0,domain=172.16.1.30,<masked> //172.16.1.43/publishingstudio$ /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pv-smb/globalmount Output: mount error(11): Resource temporarily unavailable Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

Could you help me to understand what is wrong?

Regards, 

Sébastien
