### ISSUE TITLE
smb flex volume plugin volumes timeout when fsGroup is included

### ISSUE THREAD

**Issue by Mr-Howard-Roark** [Azure/kubernetes-volume-drivers#74]
**What happened**:
[This driver](https://github.com/Azure/kubernetes-volume-drivers/blob/a4386b750afd32685e6cc353c206a8c0e583148c/flexvolume/smb/deployment/smb-flexvol-installer/smb) has been working great until I started to include a fsGroup in the Pod spec that uses a pvc that is bound to a pv that is configured to use this driver.  Example of what doesn't work (free written to give the gist of it)
```
apiVersion: v1
kind: Pod
metadata:
  name: example-doesnt-work
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: doesntwork
      image: nginx
      volumeMounts:
      - mountPath: "/test-mount"
         name: mounttotest
  volumes:
    - name: mounttotest
      persistentVolumeClaim:
        claimName: cifs-vol-created-using-flexvol-plugin-pvc 
```
The behavior I see is the pod gets stuck in a ContainerCreating state until the volume mounts timeout.  The timeouts happen consistently after 90 seconds. The logs generated by the driver output that a directory was created and the volume was successfully mounted to the node, and then at the path where it's mounted I do see that the volume is there.  So, it seems like everything is working fine, but then Kubelet somehow never mounts it into the pod and never indicates anything meaningful in its logs other than that mounting the volume timed out.

I know that there are a number of issues related to Kubelet chowning all of the files of a given volume when fsGroup is included, and potentially that's what's happening here.  But, when I include fsGroup on the same cifs shares that are instead mounted via hostPath, this issue doesn't happen.  And when I mount nfs pvs with fsGroup this issue doesn't happen either.  You would think if Kubelet is chowning all of the files when it sees fsGroup that the same timeout issues would happen regardless of whether hostPath, nfs, or this flexVolume smb driver is used.

The primary purpose of this issue is to understand whether it is expected that fsGroup can be included when using this driver.  A sub-purpose is to understand why Kubelet seems to only be chowning the files for persistent volumes created by this driver (assuming the timeouts are caused by that).

**How to reproduce it**:
Try to mount a cifs volume that was created via this driver in a pod where fsGroup is specified.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.11
- OS (e.g. from /etc/os-release): Amazon Linux 2

**Comment by andyzhangx** [comment]
Blobfuse driver does not honor `fsGroup` securityContext setting, instead user could use `-o gid=1000` in `mountoptions` to set ownership, check [here](https://github.com/Azure/Azure-storage-fuse#mount-options) for more mountoptions.

**Comment by andyzhangx** [comment]
I am not 100% sure about the `securityContext`, could you add `uid=1000,gid=1000` in your config?
```yaml
  flexVolume:
    driver: "microsoft.com/smb"
    secretRef:
      name: smbcreds
    options:
      source: "//STORAGE-ACCOUNT.file.core.windows.net/SHARE-NAME"
      mountoptions: "vers=3.0,dir_mode=0777,file_mode=0777,uid=1000,gid=1000"  # more options: https://linux.die.net/man/8/mount.cifs
```
