### ISSUE TITLE
MountVolume.SetUp failed for volume "volume2" : invalid character 's' after object key:value pair

### ISSUE THREAD

**Issue by sshorkey** [Azure/kubernetes-volume-drivers#9]
This is similar to but not the same as closed issue #3.

I'm trying to create 2 volumes:
```
      volumes:
        - name: volume
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: false
            secretRef:
              name: blobfusecreds
            options:
              container: repos
              tmppath: /tmp/blobfuse
              mountoptions: "--file-cache-timeout-in-seconds=120 --use-https=true"
        - name: volume2
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: false
            secretRef:
              name: blobfusecreds
            options:
              container: projects
              tmppath: /tmp/blobfuse
              mountoptions: "--file-cache-timeout-in-seconds=120 --use-https=true"
```
and it fails with 

> "MountVolume.SetUp failed for volume "volume2" : invalid character 's' after object key:value pair"

This is preventing the container from starting, so there's no additional logs I can give.

I am running on AKS with K8 version 1.11.4. Blobfuse driver is installed.
